[workspace]

members = [
    "amino",
    "binary_vec_io",
    "equiv",
    "io_utils",
    "mirror_sparse_matrix",
    "perf_stats",
    "pretty_trace",
    "stats_utils",
    "stirling_numbers",
    "string_utils",
    "tables",
    "vector_utils",
]

[profile.release]
debug = true
