[workspace]

members = [
    "amino",
    "ansi_escape",
    "binary_vec_io",
    "equiv",
    "graph_simple",
    "hyper",
    "io_utils",
    "kmer_lookup",
    "load_feature_bc",
    "marsoc",
    "mirror_sparse_matrix",
    "perf_stats",
    "pretty_trace",
    "stats_utils",
    "stirling_numbers",
    "string_utils",
    "tables",
    # "vdj_ann",
    "vector_utils",
]

[profile.release]
debug = true
