align_tools = "0.1.1"
amino = "0.1.2"
ansi_escape = "0.1.0"
binary_vec_io = "0.1.2"
debruijn = "0.3.2"
dna = "0.1.1"
equiv = "0.1.2"
exons = "0.1.2"
failure = "0.1.5"
fasta_tools = "0.1.2"
flate2 = "1.0.16"
graph_simple = "0.1.1"
hyperbase = "0.1.2"
io_utils = "0.2"
itertools = ">= 0.8, <= 0.9"
kmer_lookup = "0.1.1"
lazy_static = "1.3.0"
libc = "0.2.51"
load_feature_bc = "0.1.2"
lz4 = "1.23.1"
marsoc = "0.1.2"
mirror_sparse_matrix = "0.1.4"
nix = "0.13.0"
num-bigint = "^0.3"
num-rational = "^0.3"
num-traits = "^0.2"
perf_stats = "0.1.2"
permutation = "0.2.5"
petgraph = "0.4.13"
pretty_trace = "0.3.2"
rand = "0.7.3"
rayon = "1.0.2"
serde = "1.0.90"
serde_json = "1.0.41"
sha2 = "0.8.0"
stats_utils = "0.1.2"
stirling_numbers = "0.1.2"
string_utils = "0.1.1"
strum = ">=0.17.1"
strum_macros = ">=0.17.1"
superslice = "1.0.0"
tables = "0.1.2"
vdj_types = "0.1.0"
vector_utils = "0.1.3"
