align_tools = "0.1"
amino = "0.1"
ansi_escape = "0.1"
binary_vec_io = "0.1"
bio_edit = "0.1"
bio-types = "0.12"
bit-set = "0.5"
debruijn = "0.3.2"
dna = "0.1"
enum-iterator = ">=0.6, <0.8"
equiv = "0.1"
exons = "0.1"
failure = "0.1.6"
fasta_tools = "0.1"
flate2 = "1.0.20"
graph_simple = "0.1"
hyperbase = "0.1"
io_utils = "0.2"
itertools = ">= 0.8, <= 0.11"
kmer_lookup = "0.1"
lazy_static = "1.4"
libc = "0.2.85"
load_feature_bc = "0.1"
lz4 = "1.23.1"
mirror_sparse_matrix = "0.1"
nix = ">=0.19.1, <0.24"
num-bigint = "^0.3"
num-rational = "^0.3"
num-traits = "^0.2"
perf_stats = "0.1"
permutation = "0.2.5"
petgraph = "0.5"
pprof = { version = "0.6", features = ["protobuf"] }
pretty_trace = "0.5"
rand = ">=0.7.3, <0.9"
rayon = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.62"
sha2 = "0.9.3"
statrs = "0.15"
stats_utils = "0.1"
stirling_numbers = "0.1"
string_utils = "0.1"
strum = ">=0.18.0, <0.22"
strum_macros = ">=0.18.0, <0.22"
superslice = "1.0.0"
tables = "0.1"
vdj_types = "0.1"
vector_utils = "0.1"
