amino = "0.1.1"
debruijn = "0.3.2"
equiv = "0.1.1"
failure = "0.1.5"
flate2 = "1.0.16"
io_utils = "0.2.5"
itertools = ">= 0.8, <= 0.9"
kmer_lookup = "0.1.1"
lazy_static = "1.3.0"
libc = "0.2.51"
lz4 = "1.23.1"
nix = "0.13.0"
num-bigint = "^0.3"
num-rational = "^0.3"
num-traits = "^0.2"
permutation = "0.2.5"
petgraph = "0.4.13"
pretty_trace = "0.3.1"
rand = "0.7.3"
rayon = "1.0.2"
serde = "1.0.90"
serde_json = "1.0.41"
sha2 = "0.8.0"
stats_utils = "0.1.1"
string_utils = "0.1.1"
strum = ">=0.17.1"
strum_macros = ">=0.17.1"
superslice = "1.0.0"
vector_utils = "0.1.3"

exons = { path = "../exons" }
fasta = { path = "../fasta" }
graph_simple = { path = "../graph_simple" }
hyper = { path = "../hyper" }
