align_tools = { git = "https://github.com/10XGenomics/rust-toolbox.git", rev="591b502c92a7d3825fbe7bb20994e0787cc29a9d" }
amino = "0.1.4"
ansi_escape = "0.1.0"
binary_vec_io = "0.1.7"
bio = { git = "https://github.com/rust-bio/rust-bio.git", rev = "792d3e21296d85a711f1a383db513924528b6da5" }
debruijn = "0.3.2"
dna = "0.1.1"
enum-iterator = "0.6.0"
equiv = "0.1.2"
exons = "0.1.2"
failure = "0.1.6"
fasta_tools = "0.1.3"
flate2 = "1.0.20"
graph_simple = "0.1.1"
hyperbase = "0.1.2"
io_utils = "0.2"
itertools = ">= 0.8, <= 0.11"
kmer_lookup = "0.1.1"
lazy_static = "1.4"
libc = "0.2.85"
load_feature_bc = "0.1.3"
lz4 = "1.23.1"
marsoc = "0.1.2"
mirror_sparse_matrix = "0.1.10"
nix = "0.18.0"
num-bigint = "^0.3"
num-rational = "^0.3"
num-traits = "^0.2"
perf_stats = "0.1.3"
permutation = "0.2.5"
petgraph = "0.4.13"
pretty_trace = "0.4.3"
rand = "0.7.3"
rayon = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.62"
sha2 = "0.9.1"
stats_utils = "0.1"
stirling_numbers = "0.1.3"
string_utils = "0.1.1"
strum = ">=0.18.0, <0.21"
strum_macros = ">=0.18.0, <0.21"
superslice = "1.0.0"
tables = "0.1.2"
vdj_types = "0.1.2"
vector_utils = "0.1.3"
