[package]
name = "mirror_sparse_matrix"
version = "0.1.1"
authors = ["David Jaffe <david.jaffe@10xgenomics.com>"]
license = "MIT"
description = "Some tools that are 'internal' for now because they are insufficiently refined and unstable, but which are used by other 'public' crates."

[dependencies]
binary_vec_io = "0.1.1"
io_utils = "0.2.4"
pretty_trace = "0.3.1"
