[package]
name = "stirling_numbers"
version = "0.1.0"
authors = ["David Jaffe <david.jaffe@10xgenomics.com>"]

[dependencies]
num-bigint = "0.2.2"
num-rational = "0.2"
num-traits = "0.2"
rand = "0.5"
rayon = "1.0.2"
vec_utils = { git = "https://github.com/10XGenomics/rust-toolbox.git" }
