[package]
name = "vdj_ann"
version = "0.1.2"
authors = ["David Jaffe <david.jaffe@10xgenomics.com"]
edition = "2018"
license = "MIT"
description = "Some tools that are 'internal' for now because they are insufficiently refined and unstable, but which are used by other 'public' crates."
repository = "https://github.com/10XGenomics/rust-toolbox"

# This crate is not published because it is too big.

[dependencies]
align_tools = "0.1.1"
amino = "0.1.1"
bio = "0.31"
debruijn = "0.3.2"
exons = "0.1.2"
fasta_tools = "0.1.1"
flate2 = "1.0.16"
hyperbase = "0.1.1"
io_utils = "0.2"
itertools = ">= 0.8, <= 0.9"
kmer_lookup = "0.1.1"
pretty_trace = "0.3.1"
serde = "1.0.90"
serde_json = "1.0.41"
sha2 = "0.8.0"
stats_utils = "0.1.1"
string_utils = "0.1.1"
vector_utils = "0.1.3"
strum = ">=0.17.1"
strum_macros = ">=0.17.1"
