[package]
name = "vdj_ann"
version = "0.1.6"
authors = ["David Jaffe <david.jaffe@10xgenomics.com"]
edition = "2018"
license = "MIT"
description = "Some tools that are 'internal' for now because they are insufficiently refined and unstable, but which are used by other 'public' crates."
repository = "https://github.com/10XGenomics/rust-toolbox"

# This crate is not published because it is too big.

[dependencies]
align_tools = { git = "https://github.com/10XGenomics/rust-toolbox.git", rev="591b502c92a7d3825fbe7bb20994e0787cc29a9d" }
amino = "0.1.4"
bio = { git = "https://github.com/rust-bio/rust-bio.git", rev = "792d3e21296d85a711f1a383db513924528b6da5" }
debruijn = "0.3.2"
exons = "0.1.2"
fasta_tools = "0.1.3"
flate2 = "1.0.20"
hyperbase = "0.1.4"
io_utils = "0.2"
itertools = ">= 0.8, <= 0.11"
kmer_lookup = "0.1"
pretty_trace = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.62"
sha2 = "0.9.3"
stats_utils = "0.1"
string_utils = "0.1"
vector_utils = "0.1.3"
strum = ">=0.18.0, <0.21"
strum_macros = ">=0.18.0, <0.21"
vdj_types = "0.1.2"
