[package]
name = "vdj_ann"
version = "0.1.6"
authors = ["David Jaffe <david.jaffe@10xgenomics.com"]
edition = "2018"
license = "MIT"
description = "Some tools that are 'internal' for now because they are insufficiently refined and unstable, but which are used by other 'public' crates."
repository = "https://github.com/10XGenomics/rust-toolbox"

# This crate is not published because it is too big.

[dependencies]
# when bio is released again, publish align_tools, and restore this
# align_tools = "0.1"
align_tools = { git = "https://github.com/10XGenomics/rust-toolbox.git", rev="d566f5b43ae3eeaf16e5b64caf4800bed2f13d27" }
amino = "0.1"
bio = { git = "https://github.com/rust-bio/rust-bio", rev = "9f1452b128fbdbeb54d0823f6da17f40e3cc1575" }
debruijn = "0.3.2"
exons = "0.1"
fasta_tools = "0.1"
flate2 = "1.0.20"
hyperbase = "0.1.4"
io_utils = "0.2"
itertools = ">= 0.8, <= 0.11"
kmer_lookup = "0.1"
pretty_trace = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.62"
sha2 = "0.9.3"
stats_utils = "0.1"
string_utils = "0.1"
vector_utils = "0.1.3"
strum = ">=0.18.0, <0.21"
strum_macros = ">=0.18.0, <0.21"
vdj_types = "0.1.2"
