[package]
name = "pretty_trace"
version = "0.4.1"
authors = ["David Jaffe <david.jaffe@10xgenomics.com>"]
license = "MIT"
description = "Tools for generating pretty tracebacks and for profiling."
homepage = "https://github.com/10XGenomics/rust-toolbox/tree/master/pretty_trace"
keywords = ["stack", "trace", "traceback", "profiling"]
edition = "2018"

[dependencies]
backtrace = "0.3.40"
failure = "0.1.5"
io_utils = "0.2"
lazy_static = "1.3.0"
libc = "0.2.51"
nix = "0.18.0"
rayon = "1.0.2"
stats_utils = "0.1.2"
string_utils = "0.1.1"
vector_utils = "0.1.3"
