[package]
name = "pretty_trace"
version = "0.1.0"
authors = ["David Jaffe <david.jaffe@10xgenomics.com>"]

[dependencies]
backtrace = "0.3.15"
chashmap = "2.2.2"
failure = "0.1.5"
io_utils = { path = "../io_utils" }
lazy_static = "1.3.0"
libc = "0.2.51"
nix = "0.13.0"
stats_utils = { path = "../stats_utils" }
string_utils = { path = "../string_utils" }
vec_utils = { path = "../vec_utils" }
