[package]
name = "pretty_trace"
version = "0.1.0"
authors = ["David Jaffe <david.jaffe@10xgenomics.com>"]
license = "MIT"
description = "Tools for generating pretty tracebacks and for profiling."
homepage = "https://github.com/10XGenomics/rust-toolbox/tree/master/pretty_trace"

[dependencies]
backtrace = "0.3.40"
chashmap = "2.2.2"
failure = "0.1.5"
io_utils = "0.1.0"
lazy_static = "1.3.0"
libc = "0.2.51"
nix = "0.13.0"
rayon = "1.0.2"
stats_utils = { path = "../stats_utils" }
string_utils = "0.1.0"
vector_utils = "0.1.0"
