[package]
name = "pretty_trace"
version = "0.5.8"
authors = ["David Jaffe <david.jaffe@10xgenomics.com>"]
license = "MIT"
description = "Tools for generating pretty tracebacks and for profiling."
homepage = "https://github.com/10XGenomics/rust-toolbox/tree/master/pretty_trace"
keywords = ["stack", "trace", "traceback", "profiling"]
edition = "2018"

[dependencies]
backtrace = "0.3.40"
failure = "0.1.6"
io_utils = "0.2"
itertools = ">= 0.8, <= 0.11"
lazy_static = "1.4"
libc = "0.2.85"
nix = "0.19.1"
pprof = { version = "0.4.2", features = ["protobuf"] }
rayon = "1.4"
stats_utils = "0.1"
tables = "0.1"
string_utils = "0.1"
vector_utils = "0.1.3"
