[package]
name = "align_tools"
version = "0.1.0"
authors = ["David Jaffe <david.jaffe@10xgenomics.com>"]
license = "MIT"
description = "Some tools that are 'internal' for now because they are insufficiently refined and unstable, but which are used by other 'public' crates."

[dependencies]
bio = "0.31"
debruijn = "0.3.2"
itertools = ">= 0.8, <= 0.9"
vector_utils = "0.1.3"
