name: Test

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read
  # Write permissions are required in order to produce annotations.
  checks: write

jobs:
  rust:
    runs-on: ubuntu-20.04
    steps:
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.65.0
          components: rustfmt, clippy
      - name: Checkout git repository
        uses: actions/checkout@master
      - name: Check Rust formatting
        run: cargo fmt -- --check
      - name: Install cargo-deny
        run: |
          wget https://github.com/EmbarkStudios/cargo-deny/releases/download/0.13.5/cargo-deny-0.13.5-x86_64-unknown-linux-musl.tar.gz
          tar -xvf cargo-deny-0.13.5-x86_64-unknown-linux-musl.tar.gz
          mkdir -p ~/bin/
          cp cargo-deny-0.13.5-x86_64-unknown-linux-musl/cargo-deny ~/bin/
          rm -r cargo-deny-*
          echo "$HOME/bin" >> $GITHUB_PATH
      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{runner.os}}-cargo-registry-${{hashFiles('Cargo.lock')}}
          restore-keys: ${{runner.os}}-cargo-registry-
      - name: Cache cargo git index
        uses: actions/cache@v3
        with:
          path: ~/.cargo/git
          key: ${{runner.os}}-cargo-git-${{hashFiles('Cargo.lock')}}
          restore-keys: ${{runner.os}}-cargo-git-
      - name: Cache cargo build --release --all-targets
        uses: actions/cache@v3
        with:
          path: target
          key: ${{runner.os}}-cargo-target-${{hashFiles('Cargo.lock')}}-${{hashFiles('**/Cargo.toml')}}
          restore-keys: |
            ${{runner.os}}-cargo-target-
      - name: Remove the Cargo target directory
        if: github.ref == 'refs/heads/master'
        run: cargo clean
      - name: Deny duplicate dependencies and check licenses
        run: cargo deny --locked check
      - uses: 10XGenomics/clippy-check@main
        with:
          # TODO: re-enable some the -A lints below once we're clean on other
          # more important ones.
          args: |
           --all-features --all-targets --locked --release --
           -D clippy::perf
           -D clippy::style
           -D unused
           -D clippy::redundant_closure_for_method_calls
           -D clippy::wildcard_imports
           -W clippy::float_cmp
           -W future_incompatible
           -W nonstandard_style
           -W rust_2018_compatibility
           -W rust_2021_compatibility
           -F clippy::unused_io_amount
           -A clippy::many_single_char_names
           -A clippy::comparison_chain
           -A clippy::needless_range_loop
      - name: Cargo check
        run: RUSTFLAGS="-D unused -D warnings" cargo check --frozen --all-targets --release
      - name: Build tests
        run: cargo test --no-run --frozen --release
      - name: Run Rust tests
        run: cargo test --frozen --release -- --nocapture
